apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ov36420ra-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ov36420ra-dotnet-basic